"""Initial migration

Revision ID: 16ec63f87710
Revises: 
Create Date: 2026-09-15 00:16:10.053528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ec63f87710'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('study_area', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('crs', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('crs', sa.String(length=50), nullable=True),
    sa.Column('bounding_box', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_datasets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_table('preprocessing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_preprocessing_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preprocessing_jobs'))
    )
    op.create_index(op.f('ix_preprocessing_jobs_id'), 'preprocessing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_preprocessing_jobs_project_id'), 'preprocessing_jobs', ['project_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_datasets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('simulation_duration', sa.Float(), nullable=False),
    sa.Column('timestep', sa.Float(), nullable=False),
    sa.Column('output_interval', sa.Float(), nullable=False),
    sa.Column('boundary_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenarios_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_name'), 'scenarios', ['name'], unique=False)
    op.create_index(op.f('ix_scenarios_project_id'), 'scenarios', ['project_id'], unique=False)
    op.create_table('simulation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_simulation_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_simulation_jobs_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_jobs'))
    )
    op.create_index(op.f('ix_simulation_jobs_id'), 'simulation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_project_id'), 'simulation_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_scenario_id'), 'simulation_jobs', ['scenario_id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('engine_used', sa.String(length=100), nullable=False),
    sa.Column('crs', sa.String(length=50), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inundated_area_km2', sa.Float(), nullable=True),
    sa.Column('max_depth_m', sa.Float(), nullable=True),
    sa.Column('mean_depth_m', sa.Float(), nullable=True),
    sa.Column('max_velocity_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_simulation_results_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_simulation_results_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_results'))
    )
    op.create_index(op.f('ix_simulation_results_id'), 'simulation_results', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_results_project_id'), 'simulation_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_simulation_results_scenario_id'), 'simulation_results', ['scenario_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['simulation_results.id'], name=op.f('fk_export_jobs_result_id_simulation_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_jobs'))
    )
    op.create_index(op.f('ix_export_jobs_id'), 'export_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_export_jobs_result_id'), 'export_jobs', ['result_id'], unique=False)
    op.create_table('hadr_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('exposure_datasets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_hadr_analysis_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['simulation_results.id'], name=op.f('fk_hadr_analysis_result_id_simulation_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hadr_analysis'))
    )
    op.create_index(op.f('ix_hadr_analysis_id'), 'hadr_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_hadr_analysis_project_id'), 'hadr_analysis', ['project_id'], unique=False)
    op.create_index(op.f('ix_hadr_analysis_result_id'), 'hadr_analysis', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hadr_analysis_result_id'), table_name='hadr_analysis')
    op.drop_index(op.f('ix_hadr_analysis_project_id'), table_name='hadr_analysis')
    op.drop_index(op.f('ix_hadr_analysis_id'), table_name='hadr_analysis')
    op.drop_table('hadr_analysis')
    op.drop_index(op.f('ix_export_jobs_result_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_simulation_results_scenario_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_project_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_simulation_jobs_scenario_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_project_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_id'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index(op.f('ix_scenarios_project_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_name'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_preprocessing_jobs_project_id'), table_name='preprocessing_jobs')
    op.drop_index(op.f('ix_preprocessing_jobs_id'), table_name='preprocessing_jobs')
    op.drop_table('preprocessing_jobs')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_index('idx_datasets_bounding_box', table_name='datasets', postgresql_using='gist')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index('idx_projects_study_area', table_name='projects', postgresql_using='gist')
    op.drop_table('projects')
    # ### end Alembic commands ###
