"""Add lat lng to projects

Revision ID: 2112455b1377
Revises: 16ec63f87710
Create Date: 2026-09-15 06:46:44.870875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2112455b1377'
down_revision: Union[str, None] = '16ec63f87710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'longitude')
    op.drop_column('projects', 'latitude')
    # ### end Alembic commands ###
