"""add parameters to scenario

Revision ID: 38c45a198255
Revises: 51992241772b
Create Date: 2026-09-19 19:23:12.170206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38c45a198255'
down_revision: Union[str, None] = '51992241772b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_gov_infra_geom', 'government_infrastructure_features', ['geometry'], unique=False, postgresql_using='gist')
    op.add_column('scenarios', sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'parameters')
    op.drop_index('idx_gov_infra_geom', table_name='government_infrastructure_features', postgresql_using='gist')
    # ### end Alembic commands ###
