"""Add wizard models

Revision ID: 51992241772b
Revises: d0789fa32a07
Create Date: 2026-09-19 16:17:03.370186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51992241772b'
down_revision: Union[str, None] = 'd0789fa32a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_infrastructure_features',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('infrastructure_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_infrastructure_features'))
    )
    op.create_index(op.f('ix_government_infrastructure_features_id'), 'government_infrastructure_features', ['id'], unique=False)
    op.create_index(op.f('ix_government_infrastructure_features_infrastructure_type'), 'government_infrastructure_features', ['infrastructure_type'], unique=False)
    op.create_table('controlled_release_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('release_geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('discharge_type', sa.String(length=50), nullable=True),
    sa.Column('constant_discharge', sa.Float(), nullable=True),
    sa.Column('hydrograph_dataset_id', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_controlled_release_parameters_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controlled_release_parameters'))
    )
    op.create_index(op.f('ix_controlled_release_parameters_id'), 'controlled_release_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_controlled_release_parameters_scenario_id'), 'controlled_release_parameters', ['scenario_id'], unique=True)
    op.create_table('dambreak_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('breach_geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('breach_width', sa.Float(), nullable=True),
    sa.Column('breach_depth', sa.Float(), nullable=True),
    sa.Column('formation_time', sa.Float(), nullable=True),
    sa.Column('failure_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_dambreak_parameters_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dambreak_parameters'))
    )
    op.create_index(op.f('ix_dambreak_parameters_id'), 'dambreak_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_dambreak_parameters_scenario_id'), 'dambreak_parameters', ['scenario_id'], unique=True)
    op.create_table('initial_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('water_level', sa.Float(), nullable=True),
    sa.Column('storage', sa.Float(), nullable=True),
    sa.Column('discharge', sa.Float(), nullable=True),
    sa.Column('hydrograph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_initial_conditions_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_conditions'))
    )
    op.create_index(op.f('ix_initial_conditions_id'), 'initial_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_initial_conditions_scenario_id'), 'initial_conditions', ['scenario_id'], unique=True)
    op.create_table('river_blockage_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('blockage_geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('blockage_type', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('crest_elevation', sa.Float(), nullable=True),
    sa.Column('failure_mode', sa.String(length=50), nullable=True),
    sa.Column('failure_time', sa.Float(), nullable=True),
    sa.Column('breach_width', sa.Float(), nullable=True),
    sa.Column('formation_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_river_blockage_parameters_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_river_blockage_parameters'))
    )
    op.create_index(op.f('ix_river_blockage_parameters_id'), 'river_blockage_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_river_blockage_parameters_scenario_id'), 'river_blockage_parameters', ['scenario_id'], unique=True)
    op.add_column('projects', sa.Column('project_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('location_geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('projects', sa.Column('selected_dam_id', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('selected_reservoir_id', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('selected_river_id', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('dem_dataset_id', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('location_source', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('location_reference', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('data_readiness_status', sa.Float(), nullable=True))
    op.create_index(op.f('ix_projects_selected_dam_id'), 'projects', ['selected_dam_id'], unique=False)
    op.create_index(op.f('ix_projects_selected_reservoir_id'), 'projects', ['selected_reservoir_id'], unique=False)
    op.create_index(op.f('ix_projects_selected_river_id'), 'projects', ['selected_river_id'], unique=False)
    op.drop_column('scenarios', 'parameters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_selected_river_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_selected_reservoir_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_selected_dam_id'), table_name='projects')
    op.drop_index('idx_projects_location_geometry', table_name='projects', postgresql_using='gist')
    op.drop_column('projects', 'data_readiness_status')
    op.drop_column('projects', 'location_reference')
    op.drop_column('projects', 'location_source')
    op.drop_column('projects', 'dem_dataset_id')
    op.drop_column('projects', 'selected_river_id')
    op.drop_column('projects', 'selected_reservoir_id')
    op.drop_column('projects', 'selected_dam_id')
    op.drop_column('projects', 'location_geometry')
    op.drop_column('projects', 'project_type')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_river_blockage_parameters_scenario_id'), table_name='river_blockage_parameters')
    op.drop_index(op.f('ix_river_blockage_parameters_id'), table_name='river_blockage_parameters')
    op.drop_index('idx_river_blockage_parameters_blockage_geometry', table_name='river_blockage_parameters', postgresql_using='gist')
    op.drop_table('river_blockage_parameters')
    op.drop_index(op.f('ix_initial_conditions_scenario_id'), table_name='initial_conditions')
    op.drop_index(op.f('ix_initial_conditions_id'), table_name='initial_conditions')
    op.drop_table('initial_conditions')
    op.drop_index(op.f('ix_dambreak_parameters_scenario_id'), table_name='dambreak_parameters')
    op.drop_index(op.f('ix_dambreak_parameters_id'), table_name='dambreak_parameters')
    op.drop_index('idx_dambreak_parameters_breach_geometry', table_name='dambreak_parameters', postgresql_using='gist')
    op.drop_table('dambreak_parameters')
    op.drop_index(op.f('ix_controlled_release_parameters_scenario_id'), table_name='controlled_release_parameters')
    op.drop_index(op.f('ix_controlled_release_parameters_id'), table_name='controlled_release_parameters')
    op.drop_index('idx_controlled_release_parameters_release_geometry', table_name='controlled_release_parameters', postgresql_using='gist')
    op.drop_table('controlled_release_parameters')
    op.drop_index(op.f('ix_government_infrastructure_features_infrastructure_type'), table_name='government_infrastructure_features')
    op.drop_index(op.f('ix_government_infrastructure_features_id'), table_name='government_infrastructure_features')
    op.drop_index('idx_government_infrastructure_features_geometry', table_name='government_infrastructure_features', postgresql_using='gist')
    op.drop_index('idx_gov_infra_geom', table_name='government_infrastructure_features', postgresql_using='gist')
    op.drop_table('government_infrastructure_features')
    # ### end Alembic commands ###
