"""Add remaining models

Revision ID: d0789fa32a07
Revises: 6301d84c1e9f
Create Date: 2026-09-19 13:27:30.615585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd0789fa32a07'
down_revision: Union[str, None] = '6301d84c1e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_path', sa.String(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('source_agency', sa.String(), nullable=True),
    sa.Column('crs', sa.String(), nullable=True),
    sa.Column('geometry_type', sa.String(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('attribute_names', sa.JSON(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('archive_status', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('ingestion_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_datasets'))
    )
    op.create_index(op.f('ix_government_datasets_classification'), 'government_datasets', ['classification'], unique=False)
    op.create_index(op.f('ix_government_datasets_id'), 'government_datasets', ['id'], unique=False)
    op.create_index(op.f('ix_government_datasets_original_path'), 'government_datasets', ['original_path'], unique=True)
    op.create_table('government_dams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('dam_name', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('nrld_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('river_code', sa.String(), nullable=True),
    sa.Column('basin_code', sa.String(), nullable=True),
    sa.Column('dam_type', sa.String(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('spatial_data_readiness', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['government_datasets.id'], name=op.f('fk_government_dams_dataset_id_government_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_dams'))
    )
    op.create_index('idx_gov_dams_geom', 'government_dams', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_government_dams_basin_code'), 'government_dams', ['basin_code'], unique=False)
    op.create_index(op.f('ix_government_dams_dam_name'), 'government_dams', ['dam_name'], unique=False)
    op.create_index(op.f('ix_government_dams_dataset_id'), 'government_dams', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_government_dams_district'), 'government_dams', ['district'], unique=False)
    op.create_index(op.f('ix_government_dams_id'), 'government_dams', ['id'], unique=False)
    op.create_index(op.f('ix_government_dams_nrld_id'), 'government_dams', ['nrld_id'], unique=False)
    op.create_index(op.f('ix_government_dams_river_code'), 'government_dams', ['river_code'], unique=False)
    op.create_index(op.f('ix_government_dams_source_id'), 'government_dams', ['source_id'], unique=False)
    op.create_index(op.f('ix_government_dams_spatial_data_readiness'), 'government_dams', ['spatial_data_readiness'], unique=False)
    op.create_index(op.f('ix_government_dams_state'), 'government_dams', ['state'], unique=False)
    op.create_table('government_reservoirs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['government_datasets.id'], name=op.f('fk_government_reservoirs_dataset_id_government_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_reservoirs'))
    )
    op.create_index('idx_gov_reservoirs_geom', 'government_reservoirs', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_government_reservoirs_dataset_id'), 'government_reservoirs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_government_reservoirs_id'), 'government_reservoirs', ['id'], unique=False)
    op.create_index(op.f('ix_government_reservoirs_name'), 'government_reservoirs', ['name'], unique=False)
    op.create_index(op.f('ix_government_reservoirs_source_id'), 'government_reservoirs', ['source_id'], unique=False)
    op.create_table('government_river_polygons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['government_datasets.id'], name=op.f('fk_government_river_polygons_dataset_id_government_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_river_polygons'))
    )
    op.create_index('idx_gov_river_polygons_geom', 'government_river_polygons', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_government_river_polygons_dataset_id'), 'government_river_polygons', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_government_river_polygons_id'), 'government_river_polygons', ['id'], unique=False)
    op.create_index(op.f('ix_government_river_polygons_name'), 'government_river_polygons', ['name'], unique=False)
    op.create_index(op.f('ix_government_river_polygons_source_id'), 'government_river_polygons', ['source_id'], unique=False)
    op.create_table('government_rivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('river_code', sa.String(), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['government_datasets.id'], name=op.f('fk_government_rivers_dataset_id_government_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_rivers'))
    )
    op.create_index('idx_gov_rivers_geom', 'government_rivers', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_government_rivers_dataset_id'), 'government_rivers', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_government_rivers_id'), 'government_rivers', ['id'], unique=False)
    op.create_index(op.f('ix_government_rivers_name'), 'government_rivers', ['name'], unique=False)
    op.create_index(op.f('ix_government_rivers_river_code'), 'government_rivers', ['river_code'], unique=False)
    op.create_index(op.f('ix_government_rivers_source_id'), 'government_rivers', ['source_id'], unique=False)
    op.create_table('dam_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dam_id', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('match_distance', sa.Float(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dam_id'], ['government_dams.id'], name=op.f('fk_dam_relationships_dam_id_government_dams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dam_relationships'))
    )
    op.create_index(op.f('ix_dam_relationships_dam_id'), 'dam_relationships', ['dam_id'], unique=False)
    op.create_index(op.f('ix_dam_relationships_id'), 'dam_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_dam_relationships_match_status'), 'dam_relationships', ['match_status'], unique=False)
    op.create_index(op.f('ix_dam_relationships_target_id'), 'dam_relationships', ['target_id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys', ...)
    op.drop_index(op.f('ix_dam_relationships_target_id'), table_name='dam_relationships')
    op.drop_index(op.f('ix_dam_relationships_match_status'), table_name='dam_relationships')
    op.drop_index(op.f('ix_dam_relationships_id'), table_name='dam_relationships')
    op.drop_index(op.f('ix_dam_relationships_dam_id'), table_name='dam_relationships')
    op.drop_table('dam_relationships')
    op.drop_index(op.f('ix_government_rivers_source_id'), table_name='government_rivers')
    op.drop_index(op.f('ix_government_rivers_river_code'), table_name='government_rivers')
    op.drop_index(op.f('ix_government_rivers_name'), table_name='government_rivers')
    op.drop_index(op.f('ix_government_rivers_id'), table_name='government_rivers')
    op.drop_index(op.f('ix_government_rivers_dataset_id'), table_name='government_rivers')
    op.drop_index('idx_gov_rivers_geom', table_name='government_rivers', postgresql_using='gist')
    op.drop_table('government_rivers')
    op.drop_index(op.f('ix_government_river_polygons_source_id'), table_name='government_river_polygons')
    op.drop_index(op.f('ix_government_river_polygons_name'), table_name='government_river_polygons')
    op.drop_index(op.f('ix_government_river_polygons_id'), table_name='government_river_polygons')
    op.drop_index(op.f('ix_government_river_polygons_dataset_id'), table_name='government_river_polygons')
    op.drop_index('idx_gov_river_polygons_geom', table_name='government_river_polygons', postgresql_using='gist')
    op.drop_table('government_river_polygons')
    op.drop_index(op.f('ix_government_reservoirs_source_id'), table_name='government_reservoirs')
    op.drop_index(op.f('ix_government_reservoirs_name'), table_name='government_reservoirs')
    op.drop_index(op.f('ix_government_reservoirs_id'), table_name='government_reservoirs')
    op.drop_index(op.f('ix_government_reservoirs_dataset_id'), table_name='government_reservoirs')
    op.drop_index('idx_gov_reservoirs_geom', table_name='government_reservoirs', postgresql_using='gist')
    op.drop_table('government_reservoirs')
    op.drop_index(op.f('ix_government_dams_state'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_spatial_data_readiness'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_source_id'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_river_code'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_nrld_id'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_id'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_district'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_dataset_id'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_dam_name'), table_name='government_dams')
    op.drop_index(op.f('ix_government_dams_basin_code'), table_name='government_dams')
    op.drop_index('idx_gov_dams_geom', table_name='government_dams', postgresql_using='gist')
    op.drop_table('government_dams')
    op.drop_index(op.f('ix_government_datasets_original_path'), table_name='government_datasets')
    op.drop_index(op.f('ix_government_datasets_id'), table_name='government_datasets')
    op.drop_index(op.f('ix_government_datasets_classification'), table_name='government_datasets')
    op.drop_table('government_datasets')
    # ### end Alembic commands ###
