"""Add Dam3DAsset

Revision ID: e0b046bb3e86
Revises: 38c45a198255
Create Date: 2026-09-24 11:17:39.440751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e0b046bb3e86'
down_revision: Union[str, None] = '38c45a198255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dam_3d_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('asset_format', sa.String(length=10), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('origin_elevation', sa.Float(), nullable=False),
    sa.Column('rotation_x', sa.Float(), nullable=False),
    sa.Column('rotation_y', sa.Float(), nullable=False),
    sa.Column('rotation_z', sa.Float(), nullable=False),
    sa.Column('scale_x', sa.Float(), nullable=False),
    sa.Column('scale_y', sa.Float(), nullable=False),
    sa.Column('scale_z', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=False),
    sa.Column('coordinate_reference_system', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_dam_3d_assets_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dam_3d_assets'))
    )
    op.create_index(op.f('ix_dam_3d_assets_id'), 'dam_3d_assets', ['id'], unique=False)
    op.create_index(op.f('ix_dam_3d_assets_project_id'), 'dam_3d_assets', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_dam_3d_assets_project_id'), table_name='dam_3d_assets')
    op.drop_index(op.f('ix_dam_3d_assets_id'), table_name='dam_3d_assets')
    op.drop_table('dam_3d_assets')
    # ### end Alembic commands ###
