"""Add input snapshot to simulation jobs

Revision ID: e9fb2c997581
Revises: e0b046bb3e86
Create Date: 2026-09-24 14:18:38.762851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9fb2c997581'
down_revision: Union[str, None] = 'e0b046bb3e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_jobs', sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_jobs', 'input_snapshot')
    # ### end Alembic commands ###
